sudo: required

services:
  - docker

before_install:
  - docker build -t toyo-tomi/react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true toyo-tomi/react npm run test -- --coverage

# configuration for how to build production versions of all of our projects and push them to Docker Hub
after_success:
  - docker build -t sacquer/multi-client ./client
  - docker build -t sacquer/multi-nginx ./nginx
  - docker build -t sacquer/multi-server ./server
  - docker build -t sacquer/multi-worker ./worker
# log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push sacquer/multi-client
  - docker push sacquer/multi-nginx
  - docker push sacquer/multi-server
  - docker push sacquer/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-023793650799
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
