version: '3'

services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    # the host environment variables are pointing to the other services defined above.
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "/app/node_modules"
      - "./client:/app"

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - "/app/node_modules"
      - "./worker:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
